[package]
name = "dynamic_call_proc_macro"
version = "0.1.0"
edition = "2021"

license.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.67"

[lib]
proc-macro = true
